import type { Complaint, CrimeRiskRecord, UploadBatch } from "../types";

export const mockCrimeRisks: CrimeRiskRecord[] = [
  {
    id: "risk-1",
    kecamatan: "Soreang",
    kelurahan: "Soreang Kota",
    year: 2024,
    jumlahJenisAktif: 124,
    kategoriRisiko: "TINGGI",
    adaPencurian: 34,
    adaPenipuan: 12,
    adaPenganiayaan: 14,
    adaPembakaran: 2,
    adaPerkosaan: 3,
    adaNarkoba: 26,
    adaPerjudian: 6,
    adaPembunuhan: 2,
    adaPerdaganganManusia: 1,
  },
  {
    id: "risk-2",
    kecamatan: "Cilengkrang",
    kelurahan: "Melatiwangi",
    year: 2024,
    jumlahJenisAktif: 62,
    kategoriRisiko: "SEDANG",
    adaPencurian: 19,
    adaPenipuan: 8,
    adaPenganiayaan: 6,
    adaPembakaran: 1,
    adaPerkosaan: 1,
    adaNarkoba: 12,
    adaPerjudian: 2,
    adaPembunuhan: 0,
    adaPerdaganganManusia: 0,
  },
  {
    id: "risk-3",
    kecamatan: "Ciparay",
    kelurahan: "Pakutandang",
    year: 2024,
    jumlahJenisAktif: 80,
    kategoriRisiko: "SEDANG",
    adaPencurian: 22,
    adaPenipuan: 9,
    adaPenganiayaan: 11,
    adaPembakaran: 3,
    adaPerkosaan: 2,
    adaNarkoba: 15,
    adaPerjudian: 4,
    adaPembunuhan: 1,
    adaPerdaganganManusia: 0,
  },
  {
    id: "risk-4",
    kecamatan: "Cisarua",
    kelurahan: "Jambudipa",
    year: 2024,
    jumlahJenisAktif: 40,
    kategoriRisiko: "RENDAH",
    adaPencurian: 10,
    adaPenipuan: 6,
    adaPenganiayaan: 3,
    adaPembakaran: 1,
    adaPerkosaan: 0,
    adaNarkoba: 8,
    adaPerjudian: 1,
    adaPembunuhan: 0,
    adaPerdaganganManusia: 0,
  },
  {
    id: "risk-5",
    kecamatan: "Rancaekek",
    kelurahan: "Bojongloa",
    year: 2024,
    jumlahJenisAktif: 95,
    kategoriRisiko: "TINGGI",
    adaPencurian: 30,
    adaPenipuan: 14,
    adaPenganiayaan: 12,
    adaPembakaran: 4,
    adaPerkosaan: 3,
    adaNarkoba: 20,
    adaPerjudian: 7,
    adaPembunuhan: 3,
    adaPerdaganganManusia: 2,
  },
  {
    id: "risk-6",
    kecamatan: "Banjaran",
    kelurahan: "Kiangroke",
    year: 2024,
    jumlahJenisAktif: 55,
    kategoriRisiko: "SEDANG",
    adaPencurian: 17,
    adaPenipuan: 6,
    adaPenganiayaan: 7,
    adaPembakaran: 1,
    adaPerkosaan: 1,
    adaNarkoba: 9,
    adaPerjudian: 2,
    adaPembunuhan: 1,
    adaPerdaganganManusia: 0,
  },
  {
    id: "risk-7",
    kecamatan: "Dayeuhkolot",
    kelurahan: "Pasawahan",
    year: 2024,
    jumlahJenisAktif: 70,
    kategoriRisiko: "SEDANG",
    adaPencurian: 20,
    adaPenipuan: 10,
    adaPenganiayaan: 8,
    adaPembakaran: 2,
    adaPerkosaan: 1,
    adaNarkoba: 15,
    adaPerjudian: 4,
    adaPembunuhan: 1,
    adaPerdaganganManusia: 0,
  },
  {
    id: "risk-8",
    kecamatan: "Pangalengan",
    kelurahan: "Margaluyu",
    year: 2024,
    jumlahJenisAktif: 28,
    kategoriRisiko: "AMAN",
    adaPencurian: 6,
    adaPenipuan: 3,
    adaPenganiayaan: 2,
    adaPembakaran: 0,
    adaPerkosaan: 0,
    adaNarkoba: 4,
    adaPerjudian: 1,
    adaPembunuhan: 0,
    adaPerdaganganManusia: 0,
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: "comp-1",
    reporterName: "Deden R",
    reporterContact: "0812-9900-1234",
    category: "Pencurian",
    kecamatan: "Ciparay",
    kelurahan: "Pakutandang",
    description: "Motor warga hilang saat malam hari, CCTV menampilkan dua pelaku.",
    createdAt: new Date().toISOString(),
    status: "NEW",
  },
  {
    id: "comp-2",
    reporterName: "Sari M",
    reporterContact: "0813-4410-0087",
    category: "Narkoba",
    kecamatan: "Dayeuhkolot",
    kelurahan: "Pasawahan",
    description: "Ada dugaan peredaran sabu di rumah kosong dekat pasar.",
    createdAt: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
    status: "IN_PROGRESS",
  },
  {
    id: "comp-3",
    reporterName: "Yogi",
    category: "Kekerasan",
    kecamatan: "Banjaran",
    kelurahan: "Kiangroke",
    description: "Keributan antar remaja menyebabkan luka ringan, butuh patroli.",
    createdAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    status: "RESOLVED",
  },
];

export const mockUploads: UploadBatch[] = [
  {
    id: "upload-1",
    fileName: "crime-data-q1.xlsx",
    uploadedAt: "2025-01-10T09:00:00Z",
    status: "APPROVED",
    rowCount: 1800,
    errorCount: 12,
    notes: "Sudah dibersihkan dan di-crosscheck dengan kepolisian."
  },
  {
    id: "upload-2",
    fileName: "citizen-report-feb.csv",
    uploadedAt: "2025-02-04T11:15:00Z",
    status: "PENDING_REVIEW",
    rowCount: 640,
    errorCount: 4,
  },
  {
    id: "upload-3",
    fileName: "historic-risk-2023.xlsx",
    uploadedAt: "2024-12-20T15:20:00Z",
    status: "REJECTED",
    rowCount: 3200,
    errorCount: 146,
    notes: "Format kolom kelurahan tidak konsisten."
  },
];
